"""add_assignee_email

Revision ID: f0ae0a9dbb8d
Revises: 4536cf50c35f
Create Date: 2026-07-22 08:19:23.113282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ae0a9dbb8d'
down_revision: Union[str, Sequence[str], None] = '4536cf50c35f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('assignee_email', sa.String(length=254), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'assignee_email')
    # ### end Alembic commands ###
